### ISSUE TITLE
LIP-3 Discussion

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-improvement-protocols#4]
This Issue thread is created for the discussion of LIP-3 

You can read the full LIP-3 here https://github.com/loki-project/loki-improvement-protocols/blob/master/LIPS/LIP-3.md

**Comment by Endogen** [comment]
I have to mention that the data in Figure 4 isn't correct in terms of Stellite % of hashrate of largest pool. It is currently at 60% (https://miningpoolstats.stream/stellite). So it basically is another good example for your case.

Not sure if that is worth changing the graph for but i wanted to mention it.

**Comment by KeeJef** [comment]
Closing this as we have now begun work on to implement LIP-3
