### ISSUE TITLE
Enhancing the Awareness, Utility, and Anonymity Set of Oxen - Part 1 - Web Traffic Optimization

### ISSUE THREAD

**Issue by venezuela01** [loki-project/loki-improvement-protocols#40]
# Enhancing the Awareness, Utility, and Anonymity Set of Oxen - Part 1 - Web Traffic Optimization

[ORC-8](https://github.com/oxen-io/oxen-improvement-proposals/issues/36#issuecomment-1651732483) highlights a pressing concern in the Oxen ecosystem - the underutilization of the coin with limited daily transfers, thereby reducing the practical anonymity set of Oxen. This issue warrants an in-depth discussion, best bifurcated into two aspects. Firstly, the technical aspect, which suggests suboptimal wallet experiences may be deterring user engagement, merits its own discussion. Secondly, the lack of sufficient marketing visibility for Oxen significantly contributes to its low utility and limited anonymity set. This proposal seeks to address the latter, while setting aside the technical aspects for future consideration.

The following table displays the web traffic for [oxen.io](https://www.similarweb.com/website/oxen.io/#overview), [getmonero.org](https://www.similarweb.com/website/getsession.org/#overview), and [getsession.org](https://www.similarweb.com/website/getsession.org/#overview), as per SimilarWeb:

|Website | Monthly Visits | Bounce Rate | Pages per Visit | Avg Visit Duration|
|--- | --- | --- | --- | --- |
|oxen.io | 57K | 69% | 1.32 | 20s|
|getmonero.org | 240K | 51% | 3.03 | 2min 18s|
|getsession.org | 220K | 39% | 2.15 | 2min 6s|

As shown, oxen.io receives merely 24% of getmonero.org's traffic. This underlines our understanding of Oxen's lack of visibility, further confirmed by the low transaction count on the Oxen blockchain. Even more concerning is the **average visit duration**, which is only 14% of that on Monero's site. This suggests that **users may not fully comprehend Oxen's purpose, often leaving the site within seconds**. The high bounce rate and low pages per visit indicate that our Oxen website isn't effectively educating users about what Oxen is and how to use it. If we consider all these factors, we end up with just 24% * 14% = 3% of the "Total Visit Duration" compared to Monero. Ideally, once a user lands on oxen.io, we should **provide them with engaging and digestible content to extend their stay**. An average visit duration of 20 seconds is far from optimal and suggests room for improvement. Our marketing team and user experience experts might consider collaborating to devise strategies for optimization. Here is one example that could be improved: [wOxen holders don't know where to swap wOxen with Oxen.](https://github.com/oxen-io/oxen-website/issues/61)

On the other hand, the Oxen team has proposed rebranding Oxen as the Session Network Token, which presents an opportunity to increase awareness of the token. Moreover, I propose **merging oxen.io and getsession.org to enhance exposure for the Session Network Token**, a strategy likely already suggested internally by the team. **Given comparable traffic volumes and Session's current growth rate, it is foreseeable that our traffic volume will soon surpass that of Monero**.

This is a practical approach, irrespective of whether Oxen's future lies as a privacy coin or an EVM token on a transparent chain.

As a summary, speaking in the language of the [AARRR](https://builtin.com/growth-hacking/aarrr) framework, by consolidating the less frequented oxen.io into the high-traffic getsession.org, we boost the initial 'A', **Acquisition**, for Oxen. By enhancing the website content that introduces Oxen and educates users, we amplify the subsequent 'A', **Activation**, for Oxen.

![AARRR Framework](https://builtin.com/sites/www.builtin.com/files/styles/ckeditor_optimize/public/inline-images/aarrr.jpg)

Implementing such strategies earlier would have been beneficial. However, a few years ago, it was unpredictable that Session would become Oxen's flagship product. In a parallel universe, the Oxen coin might have taken the lead, and we could be regretting not promoting the Session app on oxen.io.

Resource constraints present a significant challenge, making it difficult to develop all products to the same level of excellence, as outlined in ORC-8. Despite this, the Oxen team has successfully managed three products over the past five years: the highly successful Session, the promising Lokinet, and the less satisfactory Oxen coin. This is noteworthy, given the absence of many similar projects. The Oxen coin's underperformance isn't just a technical issue; it results from a combination of technical and promotional factors, leading to a chicken-and-egg problem. The Oxen developers push themselves too hard and assume too much responsibility for the underperformance of the Oxen coin. However, it's essential to remember that both the 'chicken' (technical aspects) and the 'egg' (marketing aspects) require careful examination in such situations. This proposal provides a marketing perspective and proposes a framework for future web traffic optimization.

**Comment by KeeJef** [comment]
> On the other hand, the Oxen team has proposed rebranding Oxen as the Session Network Token, which presents an opportunity to increase awareness of the token. Moreover, I propose merging oxen.io and getsession.org to enhance exposure for the Session Network Token, a strategy likely already suggested internally by the team. Given comparable traffic volumes and Session's current growth rate, it is foreseeable that our traffic volume will soon surpass that of Monero.

I think this is a good idea, I've communicated this with the marketing team and i think the most likely approach for Session token/SENT would be that the token information/website would exist as a subdomain https://token.gesession.org or page https://getsession.org/token this way we can merge the Oxen and Session websites and have everything in the same location.

**Comment by venezuela01** [comment]
See also [SEO Analysis of Privacy Coins](https://github.com/oxen-io/oxen-improvement-proposals/issues/59)

**Comment by venezuela01** [comment]
[Part 1 - Web Traffic Optimization] is agnostic to private/non-private coin, and https://token.getsession.org/ is online now. I'll close this issue for now, as it is somewhat 'implemented', though not my favorite way.

Anyway thanks for the work.
