### ISSUE TITLE
Comparative Analysis of Trading Pairs for Various Privacy Coins on Centralized Exchanges.

### ISSUE THREAD

**Issue by venezuela01** [loki-project/loki-improvement-protocols#58]
[ORC-8](https://github.com/oxen-io/oxen-improvement-proposals/issues/36) suggests that regulatory pressure on privacy coins is a primary reason to replace Oxen with a transparent coin. This suggestion follows the event in which the KuCoin exchange delisted Oxen.

According to [CoinMarketCap](https://coinmarketcap.com/view/privacy/), until Oct 2023, there are 15 privacy coins within the top 1000 market caps (Note 1). This research compares Oxen with other privacy coins to investigate how regulatory pressure impacts different privacy coins.

Below is a list of privacy coins, their market cap rankings, and the number of trading pairs for those coins on exchanges.

| marketcap ranking | symbol | trading pair count | exchange count |
|-------------------------|--------------------|--------------------|--------------------|
| 77                      | zcash              | 153                | 51                |
| 24                      | monero             | 124                | 47 |
| ~~143~~                     | ~~worldcoin-org~~      | ~~117~~                | |
| ~~295~~                     | ~~rlc~~                | ~~66~~                 | |
| ~~194~~                     | ~~status~~             | ~~61~~                 | |
| ~~178~~                     | ~~horizen~~            | ~~56~~                 | |
| 99                      | oasis-network      | 54                 | 31 |
| ~~335~~                     | ~~phala-network~~      | ~~48~~                 | |
| 377                     | dusk-network       | 48                 | 35 |
| ~~574~~                     | ~~firo~~               | ~~46~~                 | |
| ~~340~~                     | ~~secret~~             | ~~36~~                 | |
| 316                     | nym                | 27                 | 22 |
| 260                     | mobilecoin         | 21                 | 15 |
| ~~638~~                    | ~~pivx~~               | ~~20~~                 | |
| 233                     | beldex             | 19                 | 9 |
| ~~1000~~                    | ~~vertcoin~~           | ~~17~~                 | |
| ~~819~~                     | ~~fox-token~~          | ~~15~~                 | |
| ~~696~~                     | ~~hopr~~               | ~~13~~                 | |
| 961                     | beam               | 11                 | 7 |
| ~~229~~                     | ~~aleph-zero~~         | ~~11~~                 | |
| 482                     | pirate-chain       | 11                 | 7 |
| ~~258~~                     | ~~keep-network~~       | ~~10~~                 | |
| ~~399~~                     | ~~veruscoin~~          | ~~9~~                  | |
| 413                     | dero               | 8                  | 4 |
| ~~267~~                     | ~~0x0-ai-ai-smart-contract~~ | ~~7~~          |
| 904                     | bytecoin-bcn       | 7                  | 4 |
| ~~647~~                     | ~~findora~~            | ~~6~~                  | |
| ~~320~~                     | ~~dynex~~              | ~~6~~                  | |
| 978                     | particl            | 6                  | 6 |
| 808                     | epic-cash          | 3                  | 2 |
| ~~958~~                     | ~~colossusxt~~         | ~~3~~                  | |
| 987                     | oxen               | 3                  | 1 |
| 713                     | zano               | 3                  | 2 |

Upon examining the list, we found that Oxen has the fewest number of trading pairs on exchanges compared with other top 1000 privacy coins. On average, (top 1000) privacy coins have about 33.2 trading pairs on exchanges, with a median count of 11 trading pairs (Note 2).

| **number of privacy coins** | 15                |
|---------------------------|--------------------|

| stats                          | **trading pair count** |
|---------------------------|--------------------|
| mean                      | 33.2              |
| std                       | 45.8             |
| min                       | 3                 |
| 25%                       | 6.5                 |
| 50%                       | 11                |
| 75%                       | 37.5                |
| max                       | 153               |

This simple quantitative analysis reveals a fundamental observation: Despite concerns about regulatory pressure, the majority of privacy coins have more exchange listings than Oxen. If regulatory pressure was the primary factor behind Oxen’s delisting, it should have had a similar impact on other privacy coins.

I would like to invite [Chris McCabe](https://twitter.com/Mr_CryptoMC/), the [CEO of Oxen](https://oxen.io/blog/new-leadership-new-possibilities), to comment on this.

* How can we explain the fact that Oxen has the fewest trading pairs on exchanges?
* What specific efforts have we made in the past 3 years to increase the number of listings on exchanges?
* What is the range of listing fees in each exchange we have approached?
* What can we learn from other privacy projects which have more listings on exchanges?

Please understand, I'm not placing blame. There's significant information asymmetry between the management team and community members, making it challenging for us to contribute. It's acceptable if the team says the listing fee was too high and we couldn't afford it. At least we'd learn something. However, if the information is kept confidential by the team and the decision-making process remains unclear, we learn nothing and cannot offer assistance.

---

Note 1: There are 30+ coins in the privacy related coin shortlist of Coinmarketcap, after excluding exceptions like STATUS, which isn't a true privacy coin, there are 15 remains.

Note 2: The stats has excluded outliers which are not true privacy coins.

**Comment by venezuela01** [comment]
@KeeJef, I believe Chris do not have a Github account. However, I'd like to invite Chris for a transparent and genuine discussion. I believe that such a discussion would be valuable for the community and deserves a public archive. Could you please remind him to comment on this post? I would greatly appreciate it.

**Comment by venezuela01** [comment]
Despite there are only 15 privacy coins within top 1000 market cap, these 15 privacy coins are listed in 108 different exchanges. This is a typical example of long tail distribution and an interesting demonstration of decentralization, where a few top exchanges list only a few privacy coins, while a large number of tail exchanges list a very diverse portfolio of different privacy coins.

[privacy_exchanges_list.csv](https://github.com/oxen-io/oxen-improvement-proposals/files/13168347/privacy_exchanges_list.csv)

Here are the top 60 exchanges sorted by number of privacy coin trading pairs listed extracted from the above attachment.

Exchange | Count of unique Privacy Coins | Count of Privacy Coin Trading Pairs
-- | -- | --
Gate.io | 10 | 20
HitBTC | 7 | 19
CoinEx | 10 | 19
Binance | 5 | 18
Nominex | 5 | 15
CoinDCX | 6 | 12
Bitrue | 5 | 11
KuCoin | 6 | 11
Kraken | 3 | 10
Bitfinex | 4 | 9
MEXC | 8 | 9
PayBito | 2 | 9
Poloniex | 4 | 9
FMFW.io | 3 | 8
Pionex | 6 | 8
TradeOgre | 5 | 8
OKX | 3 | 8
Coinut | 2 | 7
WazirX | 4 | 6
DigiFinex | 3 | 6
LATOKEN | 4 | 6
Bittrex Global | 3 | 6
ViteX | 3 | 5
BingX | 5 | 5
SafeTrade | 3 | 5
BigONE | 3 | 5
Bitcoiva | 3 | 5
HTX | 4 | 4
XT.COM | 2 | 4
Gemini | 1 | 4
Tokocrypto | 3 | 4
Hotcoin Global | 4 | 4
Bitbns | 3 | 4
Binance.US | 2 | 4
Coinbase Exchange | 2 | 4
Coinlist Pro | 2 | 4
Koinpark | 2 | 4
LBank | 3 | 3
BTSE | 1 | 3
Dex-Trade | 1 | 3
Deepcoin | 3 | 3
BTX Pro | 1 | 3
Jubi | 2 | 3
Cryptology | 1 | 3
Bitazza | 1 | 3
Coinsbit | 1 | 3
CoinW | 3 | 3
WhiteBIT | 2 | 3
PancakeSwap v3 | 2 | 3
ProBit Global | 1 | 2
ZebPay | 2 | 2
PancakeSwap v2 (BSC) | 2 | 2
BYDFi | 2 | 2
P2B | 1 | 2
YoBit | 1 | 2
OceanEx | 1 | 2
AscendEX (BitMax) | 2 | 2
LocalTrade | 1 | 2
NexDAX | 1 | 2
KoinBX | 1 | 2

**Comment by venezuela01** [comment]
[privacy_exchanges_list_with_symbol.csv](https://github.com/oxen-io/oxen-improvement-proposals/files/13168621/privacy_exchanges_list_with_symbol.csv)

**Comment by venezuela01** [comment]
**Update**:

Upon examining [SimpleSwap](https://simpleswap.io/coins), it's observed that:

- SimpleSwap supports 11 out of the 15 privacy coins mentioned on [comment 1](https://github.com/oxen-io/oxen-improvement-proposals/issues/58#issue-1960857401).
- The privacy coins that are not supported include: Bytecoin, Particl, Oxen, and Zano.
- Note that SimpleSwap only supports the wrapped tokens of Dusk and NYM, not their original native coins.

Similarly, for [ChangeNow](https://changenow.io/currencies):

- ChangeNow supports 8 out of the 15 privacy coins listed in the aforementioned [comment 1](https://github.com/oxen-io/oxen-improvement-proposals/issues/58#issue-1960857401).
- The unsupported privacy coins are: MobileCoin, Beldex, Pirate Chain, Dero, Bytecoin, Particl, Oxen, and Zano.
- Notably, ChangeNow supports only the wrapped tokens of Dusk, NYM, and Pirate Chain, not the native versions.

See also [Enhance Oxen's Interoperability and Connectivity via Centralized Swapping Services Integration in Oxen Wallet](https://github.com/oxen-io/oxen-improvement-proposals/issues/55)

**Comment by KeeJef** [comment]
This is a complex issue, many of the privacy coins you've listed do not have default opt out privacy like Oxen/Monero, which makes things more complex from a regulatory perspective. There is also the matter of market cap, exchanges are less willing to jump through hoops to support unique forks, with opt out privacy, with relativity low market caps. 

This is also a forward looking issue exchanges are increasingly moving away from privacy coins, https://finance.yahoo.com/news/binance-delist-monero-zcash-4-153904972.html? and https://www.coindesk.com/business/2022/09/12/crypto-exchange-huobi-to-delist-7-privacy-coins-including-zcash-monero/ i expect these announcements to continue on the major exchanges over 2024

**Comment by venezuela01** [comment]
> This is a complex issue, many of the privacy coins you've listed do not have default opt out privacy like Oxen/Monero, which makes things more complex from a regulatory perspective.

Zcash on the list does not have default opt-out privacy like Oxen/Monero; however, the majority of the coins I listed do have opt-out privacy. I edited my post and reduced the list from over 30 coins to 15 coins before your comment. If you read my original post from an email rather than the Github web UI, you might have missed my editing.

> This is also a forward looking issue exchanges are increasingly moving away from privacy coins, https://finance.yahoo.com/news/binance-delist-monero-zcash-4-153904972.html? and https://www.coindesk.com/business/2022/09/12/crypto-exchange-huobi-to-delist-7-privacy-coins-including-zcash-monero/ i expect these announcements to continue on the major exchanges over 2024

A few top exchanges are removing privacy coins; however, there are always smaller exchanges that do not mind supporting privacy coins. As my data shows, 15 privacy coins are listed on 108 different exchanges, demonstrating the importance of decentralization in defending privacy.

You didn't answer my questions, though:

* What specific efforts have we made in the past 3 years to increase the number of listings on exchanges?
* What is the range of listing fees in each exchange we have approached?
* What can we learn from other privacy projects which have more listings on exchanges?

**Comment by venezuela01** [comment]
> This is also a forward looking issue exchanges are increasingly moving away from privacy coins, https://finance.yahoo.com/news/binance-delist-monero-zcash-4-153904972.html? and https://www.coindesk.com/business/2022/09/12/crypto-exchange-huobi-to-delist-7-privacy-coins-including-zcash-monero/ i expect these announcements to continue on the major exchanges over 2024

The report on https://coindelist.com/app/reports (login required) indicates that between 2023-10-07 and 2023-10-30, a total of 190 trading pairs were delisted by at least six exchanges (Binance, OKEx, Gate.io, Kucoin, Poloniex, Huobi). These delistings encompass 159 target tokens and 10 counterparty tokens (such as USDT, BTC, ETH, BUSD, etc.). It's noteworthy that this data, spanning the entire duration mentioned without any exclusions, represents the full extent of the historical data provided by coindelist.com as of the time of writing, unfortunately constituting a not very large time window.

### Exchange-wise Delisting Stats

| Exchange | Delisted Pairs | Partial Delisted Token | Completely Delisted Token | Notes |
|----------|----------------|----------------|----------------|----------------|
| Binance  | 102            | 95 | 0 |  [note](https://www.binance.com/en/feed/post/1080280) |
| OKEx     | 25             | 11 | 12 | |
| Gate.io  | 19             | 0 | 10 | |
| Kucoin   | 19             | 0 | 13 | |
| Poloniex | 17             | 0 | 17 | |
| Huobi    | 8              |0 | 5 | |

### Counterparty Token Analysis

| Counterparty Token | Number of Associated Delisted Pairs | Notes |
|--------------------|--------------------|--------------------|
| BUSD               | 89                 | [note](https://www.binance.com/en/feed/post/1080280)
| USDT               | 56                 |
| ETH                | 15                 |
| BTC                | 11                 |
| BNB                | 6                  |
| EUR                | 6                  |
| USDC               | 3                  |
| OKB                | 2                  |
| KCS                | 1                  |
| GBP                | 1                  |

### Special Case: Binance and BUSD

**Edited:** Among the 190 delisted trading pairs, 89 pairs from Binance are associated with BUSD. This is because [Binance is gradually delisting BUSD](https://www.binance.com/en/feed/post/1080280); however, this is not relavent to our research. **Therefore, we should exclude these 89 pairs.** Note that this exclusion also removes the ZEC/BUSD pair from consideration, where ZEC is partially removed from Binance rather than completely removed. Of the remaining 101 trading pairs, none involve a native privacy coin being completely removed.

### Privacy Features Analysis

Among the 57 completely removed tokens, TORN is the only smart contract token offering a privacy mixing function.

56 out of 57 (98%) remaining delisted tokens are all transparent tokens or coins with no association to privacy transaction technologies., including:
* transparent smart contract tokens (>=72% out of 56), or
* transparent native coins (the remaining out of 56)

**There is no statistical evidence to suggest that privacy coins are more likely to be delisted compared to non-privacy coins.**

### Token Type Analysis

26 out of 57 (46%)  being ERC20 tokens, and 7 of 57 (12%) claim themselves as DeFi projects. 

| Smart Contract Platform           | Number of Completely Delisted Tokens |
|--------------------|---------------------------|
| Ethereum           | 26                        |
| BNB                | 10                        |
| Terra-Luna         | 2                         |
| Arbitrum           | 1                         |
| Chiliz             | 1                         |
| Tron               | 1                         |

### Market Cap Relevance

CoinMarketCap Ranking Stats of Completely Delisted Tokens:

| Stat | Value |
|------|-------|
| Min  | 718     |
| 25%  | 1489   |
| 50%  | 2104   |
| 75%  | 3962  |
| Max  | 4995  |

**Edited:**
Out of the 57 completely delisted tokens, the minimum market cap rank is 718, with a median market cap rank of 2104. **This suggests that market cap is a more relevant factor when it comes to a token being completely delisted**, especially after updating the methodology to exclude BUSD pairs and counting only completely removed tokens rather than partially delisted tokens.

(Note: The CoinMarketCap API only supports the top 5000 tokens. 9 out of the 57 tokens failed to match with the CoinMarketCap top 5000 tokens.)

### Referrence Resources

[crypto_delisted_report_2023_10_31.csv](https://github.com/oxen-io/oxen-improvement-proposals/files/13215051/crypto_delisted_report_2023_10_31.csv)

[coindelist_raw_report.csv](https://github.com/oxen-io/oxen-improvement-proposals/files/13215586/coindelist_raw_report.csv)

[coinmarketcap_listings_2023_11_01.csv](https://github.com/oxen-io/oxen-improvement-proposals/files/13220583/coinmarketcap_listings_2023_11_01.csv)

See also [8 Reasons Coins Get Delisted From Cryptocurrency Exchanges](https://medium.com/efficient-frontier/six-reasons-coins-get-delisted-from-crytpocurrency-exchanges-3666deb1ef9f) and [Delisting | Binance Academy](https://academy.binance.com/en/glossary/delisting)

**Comment by venezuela01** [comment]
Update:

Kucoin has recently (2023-11-22) promoted BeldexCoin, a fork of the Oxen privacy coin. Consider Kucoin delists Oxen while promoting Beldex, there is no evidence that being a privacy coin is a major factor in the delisting decision from Kucoin.

* [Kucoin Twitter Post](https://twitter.com/kucoincom/status/1727265674865828074)
* [Kucoin Announcement: BDX Quiz Campaign: Join To Get a Share of $2,000 in BDX!](https://www.kucoin.com/announcement/-en-bdx-quiz-campaign-join-to-get-a-share-of-$2,000-in-BDX-20231122)

**Comment by venezuela01** [comment]
@msgmaxim

**Comment by venezuela01** [comment]
https://token.getsession.org/ is now live. The new Session Token will launch on Arbitrum as a transparency token and will be supported by various decentralized and centralized exchanges. There is little value in keeping this report open.

**@KeeJef is correct about the trend in privacy coin regulation**, as [Monero was recently delisted from Binance](https://www.binance.com/en/support/announcement/binance-will-delist-ant-multi-vai-xmr-on-2024-02-20-f73b083ba6834771b07dbe5319917ae5). I can understand the choice made by the Oxen team to move away from a privacy coin. With that said, I hold more respect for the privacy coin community, like Monero. Even though they got delisted, they are still working on privacy-centric DEXes. Good luck to them.

Solana also announced [native private transfers](https://www.helius.dev/blog/all-you-need-to-know-about-solanas-v1-16-update) a few months ago. I'm not sure if it would have been better to migrate Oxen to Solana rather than Arbitrum. Let's see how well those EVM privacy solutions integrate with the new Session token. This will take some time.

Closing.
