### ISSUE TITLE
Enhancing Oxen/Session/Lokinet development with David R. MacIver's Software Development Management Coaching

### ISSUE THREAD

**Issue by venezuela01** [loki-project/loki-improvement-protocols#61]
Congratulations on the successful launch of Chainflip.

Both Chainflip and Oxen have been in development for many years. While ChainFlip is finally gaining momentum, Oxen still has a long journey ahead.

To accelerate the development of Oxen/Session/Lokinet, I propose consulting David R. MacIver, a distinguished software developer turned consultant and coach. His expertise could significantly enhance our software development management, technical decision-making, and overall software quality.

### Why Do We Need a Software Development Management Consultant?

1. **Addressing Development Challenges**: We've faced significant hurdles, including persistent bugs, a slow development pace, and challenges in estimating timelines, and many more. These issues have impacted our user experience, as evidenced by the decline in the Session Android app's rating from 4.2 to 3.5 over the past eight months, according to [AppBrain](https://www.appbrain.com/app/session-private-messenger/network.loki.messenger#ratinghistory). Addressing these issues is crucial for our success and user satisfaction.

2. **Strategic Growth with New Funding**: The recent influx of funds from the FLIP token listing presents an opportunity to expand our team. It's essential to grow in a direction grounded in sound principles and best practices. As our team grows, effective decision-making becomes increasingly important. Now is the perfect time to benefit from a top expert's proven experience and methodology.

### Why David R. MacIver?

David has over a decade of experience in software development, ranging from startups to Google, and managing the influential open-source project Hypothesis. He focuses not only on software systems but also on the human elements behind them, offering decision support, process improvements, and enhanced team dynamics.

His services include one-on-one coaching for senior roles, group coaching for team challenges, and courses to develop crucial soft skills for teamwork. These offerings are tailored to address issues like prolonged code reviews, recurring bugs, open source contribution and community communication.

David's expertise will be invaluable to us. His approach to identifying and implementing small, incremental improvements can enhance our work seamlessly without abrupt conflicts and interruptions.

Please consider this proposal. I am happy to coordinate or provide additional information as needed.

**Comment by venezuela01** [comment]
Quote from https://consulting.drmaciver.com/

###  Consulting with David R. MacIver

I help software companies understand and improve the human systems they depend on.

Hi, I’m David R. MacIver. I’m a software developer turned consultant and coach.

I worked for over over a decade as a software developer. First, in increasingly senior roles at a series of startups, then at Google, and finally running an open-source project, [Hypothesis](https://github.com/HypothesisWorks/Hypothesis/), which redefined the state-of-the-art in usability of property-based testing across any language. Many of the big-name Python projects now use it to find bugs in their code, including the Python standard library itself and NumPy. Many companies and smaller open source projects use it too: Hypothesis gets over [two million downloads per month](https://pypistats.org/packages/hypothesis), and 4% of developers who answered [the 2020 Jetbrains survey](https://www.jetbrains.com/lp/python-developers-survey-2020/) said they are using Hypothesis!

I have now mostly handed over the reigns on Hypothesis to others, and now work as a writer, coach, and consultant, focusing not just on software systems, but on the _human systems_ that produce them, and how we can make those human systems better. I provide one-on-one and group support, primarily aimed at helping technical people with people problems including decision support, software development processes, and developing soft skills that help them work better together as a team.

Many companies work like badly maintained software projects: Everything more or less works, but not _well_. Really serious problems get fixed, but an accumulation of many small problems means nothing works as you’d like it to. The result is a constant drag on teams’ morale and ability to work effectively, and things take longer and seem harder than they should, often without any clearly identifiable root cause.

For example:

*   Code is sitting around in review for ages.
*   Embarrassing bugs routinely reach production.
*   Work takes too long because the wrong thing is being made, or the specifications are continually being revised.
*   Tasks often take much longer to complete than estimated.
*   People constantly feel overwhelmed with more work than they can get done.
*   People feel disconnected from each other and lack a shared sense of purpose, often leading to disagreements about what should be done.

Often these problems feel like they’re just facts of life or are too hard to fix. Even the ones that seem fixable, you don’t ever find time to prioritise because how do you choose between dozens of issues of seemingly equal and minor importance? There’s no looming catastrophe, but it feels like things could be much better, and you feel stuck as to how to get there.

The bad news is that there is no magic fix or methodology that will make all of this go away. The good news is that there are many easily accessible small, incremental, interventions that will make things better immediately, and that by consistently identifying those and gradually implementing over time, many small benefits accrue into large improvements. I can help you find those interventions.

I think of my work as helping people learn to maintain the human systems that underly our software development. These human systems are at least as complex as software systems, but are rarely treated this way. When software has a problem that affects production, you investigate it, debug it, and fix it. I can help you do this.

I offer three main types of service in support of this:

*   One-on-one coaching for people in senior roles. This can be individual contributors struggling with specific issues, team leads, or CTOs. I’m particularly keen on providing ongoing one-on-one coaching for CTOs, as this is among the most interesting and valuable work I can do.
*   Group coaching sessions for teams who are struggling with particular problems. This can be anything, but most often focuses on support for specific decisions (e.g. planning a particular big project, restructuring their work practices) or on helping identify and develop the skills they need for a particular pattern of ongoing problem.
*   90 minute group classes for helping developers acquire crucial soft skills that allow them to work more effectively as teams. [You can see the full list of classes here](https://consulting.drmaciver.com/courses/), but they include topics such as communication skills, decision making, and estimation.

**Comment by venezuela01** [comment]
@KeeJef @jagerman

**Comment by venezuela01** [comment]
See also [Top 20 User Complains of Session Android Based on Google Play Reviews](https://github.com/oxen-io/session-android-temp/issues/90)

**Comment by KeeJef** [comment]
I've reached out via email to David, i am open to suggestions and consulting to improve our processes

**Comment by venezuela01** [comment]
> I've reached out via email to David, i am open to suggestions and consulting to improve our processes

I greatly appreciate and am heartened by your initiative in reaching out to David.

Although I have concerns about the current development process, my limited visibility prevents me from making responsible suggestions. I believe David, with his extensive experience, is far better positioned to offer valuable insights.

On a personal note, I highly regard Douglas Hubbard's books, [How to Measure Anything: Finding the Value of Intangibles in Business](https://www.amazon.com.au/How-Measure-Anything-Intangibles-Business-ebook/dp/B00INUYS2U) and [How to Measure Anything in Cybersecurity Risk](https://www.amazon.com.au/How-Measure-Anything-Cybersecurity-Risk/dp/1536669741), as well as other books from him. I've applied some of his techniques in my own work, but I'm convinced there's more potential to explore in his methodology. His books are accessible; dedicating about 30 minutes a day, one could likely complete a book in less than a month, including exercises. For those without a strong background in mathematics, skipping the detailed math can still allow them to gain a decent understanding of the principle.

In addition to benefiting from Hubbard's methodology, I am also a practitioner and believer in [Market-Based Management](https://www.principlebasedmanagement.com/). I've found that the techniques from "How to Measure Anything" surprisingly complement some of the gaps in the Market-Based Management approach as outlined in the books [The Science of Success](https://en.wikipedia.org/wiki/The_Science_of_Success) and [Good Profit](https://en.wikipedia.org/wiki/Good_Profit). However, these latter two books can be challenging and boring without a solid foundation in economics, and they omit many details I feel could have been expanded upon. The author, Charles Koch, is a successful entrepreneur but not necessarily a very good writer. I wouldn't recommend investing time in these two books, but I might reference specific chapters when commenting about the Oxen project in the future.

**Comment by KeeJef** [comment]
Unfortunately i have not received a reply from David in a few months since i sent an email to him

**Comment by venezuela01** [comment]
> Unfortunately i have not received a reply from David in a few months since i sent an email to him

Sorry to hear that, but thanks for trying; I'll remind him. He is on Discord and Twitter, I'll ask him to check his email. My only concern is whether he still has any free slots for new projects.

**Comment by venezuela01** [comment]
@KeeJef, David says he doesn't have time for consulting at the moment and will have to update his consulting site to reflect that.

When I asked him if there was someone he really respects and could recommend, he said https://sixty-north.com/ is currently looking to pick up more consulting and contracting work. He rates them highly, and they are very experienced software engineers. However, they are more focused on the technical side, less so on methodology compared to David himself. Nonetheless, he still believes that Rob and Austin at Sixty North are worth talking to.

BTW, Daivid said he didn't receive any email from you but he can receive my test email. Remember in https://github.com/oxen-io/oxen-core/issues/1650#issuecomment-1823594865 we had another instance where you sent an email but didn't receive a reply? Is there any chance there is an issue with your mail server? It seems like this issue is quite important if it happens repeatedly.

**Comment by KeeJef** [comment]
Strange i don't seem to have many other issues with Emails reaching their sources, on the linked issue, that was not an email, it was a Avast report that i filled in through their website. I will look at reaching out to Sixty North

**Comment by venezuela01** [comment]
Hi @KeeJef, David is [looking for new projects recently](https://drmaciver.substack.com/p/looking-for-new-projects), do you still think it's a good idea to have a chat with him? You can find his email in the link or [book a meeting](https://calendly.com/drmaciver/consulting-intro).

**Comment by KeeJef** [comment]
I will reach out and see how this could work

**Comment by venezuela01** [comment]
> I will reach out and see how this could work

Thank you!

**Comment by venezuela01** [comment]
Hi @KeeJef, thanks again for consider the suggestion. Have you finally heard back from David? Did you find any opportunity to use David's expertise, or was that not a very good fit? No rush, I'm asking just because there are other suggestions on my to-do list, which I'm waiting for a good time to share.

**Comment by KeeJef** [comment]
I reached out again next week, haven't heard back yet

**Comment by venezuela01** [comment]
> I reached out again next week, haven't heard back yet

Maybe try to book a meeting directly and have a quick chat to decide if it worth to move on?

https://calendly.com/drmaciver/consulting-intro

**Comment by KeeJef** [comment]
I've booked something now on the calendar, ill see how it goes, times are a little tricky for Melbourne

**Comment by venezuela01** [comment]
> I've booked something now on the calendar, ill see how it goes, times are a little tricky for Melbourne

I see, thanks for trying!

**Comment by venezuela01** [comment]
Hi @KeeJef , have you had a chance to explore opportunities to utilize David's skills to benefit the Session project? Feel free to let me know if there's anything else I can do to assist.

**Comment by KeeJef** [comment]
Hey @venezuela01 I was able to jump on a call with David last week, unfortunately it sounds like he isn't really doing coaching anymore. So I think we are out of luck on that avenue

**Comment by venezuela01** [comment]
> Hey @venezuela01 I was able to jump on a call with David last week, unfortunately it sounds like he isn't really doing coaching anymore. So I think we are out of luck on that avenue

Hi @KeeJef Thanks again for trying! No worries, I'll move on to share my plan B suggestions in other posts.

By the way, one thing I think worth considering is to ask David to guide the Session team to implement property-based testing to thoroughly cover critical parts of the Session project, including libsession config syncing/merging, the close group protocol, the lokinet protocol, etc. These parts are often hard to get right and prone to errors, and property-based testing is almost the only technique that can improve the guarantee of these components. However, I consider this a relatively smaller scope and less urgent goal compared to the original proposal of improving overall development management. I trust you to decide the priority, the best timing, and the best person for this subgoal.

**Comment by venezuela01** [comment]
I appreciate @KeeJef's effort for reaching out to David. Unfortunately, David is no longer offering coaching. As a result, I'm closing this proposal. However, I think some (but not all) of the original concerns motivating this proposal could potentially be addressed by another proposal in [Embrace Lean Startup Methodology for the Session Project](https://github.com/oxen-io/oxen-improvement-proposals/issues/67). I'll move the remaining discussion there when appropriate.
